#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
rm -rf $DIR/output
sass $DIR/themes/tymify/assets/sass/app.scss > $DIR/themes/tymify/assets/css/theme.css
nikola build && nikola serve 
